[package]
name = "numfmt"
version = "0.1.0"
authors = ["Kurt Lawrence <kurtlawrence.info>"]
edition = "2021"
description = "Fast and friendly Rust number formatting"

[lib]
path = "lib.rs"

[dependencies]
dtoa = "1"
itoa = "1"

[dev-dependencies]
criterion = "*"

[[bench]]
name = "numfmt-benchmarks"
path = "bench.rs"
harness = false
